### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by NickyTesla** [geoffrich/sveltekit-is-land#2]
Hi, I have this running in dev, but I'm running into issues during the build step both on my local machine, and when I deploy it.

`Cannot convert undefined or null to object
error during build:
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at resolveBuildOutputs (file:///Users/n/Desktop/sveltekit-is-land/node_modules/vite/dist/node/chunks/dep-2faf2534.js:45873:20)
    at doBuild (file:///Users/n/Desktop/sveltekit-is-land/node_modules/vite/dist/node/chunks/dep-2faf2534.js:45739:25)
    at async build (file:///Users/n/Desktop/sveltekit-is-land/node_modules/vite/dist/node/chunks/dep-2faf2534.js:45620:16)
    at async CAC.<anonymous> (file:///Users/n/Desktop/sveltekit-is-land/node_modules/vite/dist/node/cli.js:756:9)`

Any ideas about what might be going on?

**Comment by NickyTesla** [comment]
removing 
`
			lib: {
				formats: ['es']
			},
`

from the islands.config.js file allows the build to continue, but the the outputted [Component].js files themselves are empty...  Their corresponding css files are extracted and written correctly though, so it looks like the [Component].svelte files are being read.

**Comment by jenniferworrall** [comment]
It seems to require an entry or list of entries in the vite config file now in the build section for Vite 4.  I still haven't gotten a working build yet but this helped!
